### PR TITLE
Search box in scenario management elements selector control

### LINKED ISSUE #1305: Scenario selector - Search bar
### Description

We want a search bar in the scenario selector to help end-users quickly find scenarios.

### Solution Proposed

A search property is exposed to activate/deactivate the search bar. By default, it is activated.

When an end-user provides text in the search bar (the search input), the system finds matching scenarios (the search result). The matching is performed using the scenario labels. Only the scenarios containing the search input must appear in the search result.
Neither the search input nor the search result are shared among end-users. The search bar acts as a client-side filter on the list of scenarios to display, so the bound variables are not modified.

Default: By default, the developer should not need to do anything:
```<| {selected_scenario} | scenario_selector |>```

Deactivate: If he/she wants to deactivate the filtering mechanism:
```<| {selected_scenario} | scenario_selector | search=False |>```

### Impact of Solution

_No response_

### Additional Context

_No response_

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by FredLL-Avaiga**
resolves #1305
image
image

### CODE REVIEW

**Review by dinhlongviolin1 — APPROVED** [review]
The search is local which I think is great

**Review by dinhlongviolin1 — DISMISSED** [review]
LGTM

**Review by FabienLelaquais — APPROVED** [review]
Couldn't spot anything wrong there.
Nice piece of code, again!

**Comment by FabienLelaquais** [comment]
Please create a referencing issue pointing here. This UX is pretty bad in my opinion.

**Pull request merged**
