### PR TITLE
Usage examples for analogic option in date picker and date range

### PR DESCRIPTION
**Pull request by Tryxns**
A complimentary PR for https://github.com/Avaiga/taipy/pull/2116 and https://github.com/Avaiga/taipy/pull/2115

### CODE REVIEW

**Comment by Tryxns** [comment]
Hello @FredLL-Avaiga , please take your time to review this :pray:

**Review by FredLL-Avaiga — APPROVED** [review]
tx @Tryxns 
Looks good to me

**Comment by FredLL-Avaiga** [comment]
How do you like it @FabienLelaquais ?

**Comment by Tryxns** [comment]
Hi @FredLL-Avaiga @jrobinAV can we merge this today please?

**Comment by FredLL-Avaiga** [comment]
> Hi @FredLL-Avaiga @jrobinAV can we merge this today please?

What do you think @FabienLelaquais ?

**Comment by Tryxns** [comment]
Hi Mr. @FabienLelaquais please let me know your thought about my PR 🙂 
Since every mode option in component has its own example (CMIIW), I think the new `analogic ` mode deserve examples too

**Review by FabienLelaquais — APPROVED** [review]
That's fine!

**Comment by FabienLelaquais** [comment]
> Hi Mr. @FabienLelaquais please let me know your thought about my PR 🙂 Since every mode option in component has its own example (CMIIW), I think the new `analogic ` mode deserve examples too

I completely agree. Your examples are short, simple, and show the one thing they need to show.
To me, that's neat.

Thank you!

**Comment by RymMichaut** [comment]
@Tryxns just to let you know that this PR has been added to your list and you'll get its swag :)

**Comment by Tryxns** [comment]
Thank you @RymMichaut ✨️

**Pull request merged**
