### PR TITLE
chat support markdown pre raw

### LINKED ISSUE #1807: Chat controls support different rendering mode like Text
### Description

It would be good to have chat controls support different rendring mode like Text. So it can handle markdown properly. 

### Solution Proposed

_No response_

### Impact of Solution

_No response_

### Additional Context

_No response_

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by FredLL-Avaiga**
resolves #1807
```
from typing import List

import numpy as np

import taipy.gui.builder as tgb
from taipy.gui import Gui, Icon, State, notify


def request(state: State, prompt: str) -> str:
    """
    Send a prompt to the GPT-4 API and return the response.

    Args:
        - state: The current state of the app.
        - prompt: The prompt to send to the API.

    Returns:
        The response from the API.
    """
    random_response = [
        "How are you?",
        "What are you doing?",
        "What is your name?",
        "Who are you?",
    ]

    return random_response[np.random.randint(0, 4)]


# Initialize conversation context
base_conversation: List[List[str]] = [
    ["1", "Who are you?", "Human"],
    ["2", "Hi! I am GPT-4. How can I help you today?", "AI"],
]
conversation = None
users: List[List[str | Icon]] = [
    ["Human", Icon("/images/human_icon.png", "Human.png")],
    ["AI", Icon("/images/ai_icon.png", "AI.png")],
]


def on_init(state: State) -> None:
    """
    Initialize the app.

    Args:
        - state: The current state of the app.
    """
    state.conversation = base_conversation.copy()



def send_message(state: State, var_name: str, payload: dict = None) -> None:
    """
    Send the user's message to the API and update the context.

    Args:
        - state: The current state of the app.
    """
    if payload:
        args = payload.get("args", [])
        current_user_message = args[2]
        sender = args[3]

        notify(state, "info", "Sending message...")
        answer = request(state, current_user_message).replace("\n", "")

        state.conversation += [
            [
                f"{len(state.conversation) + 1}",
                current_user_message,
                sender,
            ]
        ]

        state.conversation += [[f"{len(state.conversation) + 1}", answer, "AI"]]
    notify(state, "success", "Response received!")



# Building the layout
with tgb.Page() as page:
    tgb.toggle(theme=True)
    tgb.chat(
        "{conversation}",
        users=users,
        on_action=send_message,
        sender_id="Human",
        show_sender=True,
        height="80vh",
        mode="md",
    )


# Main entry point
if __name__ == "__main__":
    client = None

    gui = Gui(page)
    gui.run(title="Taipy Simple Chat")

```

### CODE REVIEW

**Review by FabienLelaquais — DISMISSED** [review]
Brilliant!

**Review by dinhlongviolin1 — DISMISSED** [review]
Too easy for you

**Review by namnguyen20999 — DISMISSED** [review]

**Review by namnguyen20999 — DISMISSED** [review]

**Review by FabienLelaquais — DISMISSED** [review]
🤔

**Review by namnguyen20999 — DISMISSED** [review]

**Review by namnguyen20999 — APPROVED** [review]
lgtm

**Pull request merged**
