### PR TITLE
[DOCS] Add Image Badges

### LINKED ISSUE #1934: [DOCS] Add Badges
### Issue Description

I would like to add interactive badges in a table format, int the header-section of the README documentation. This will enhance the Engagement & interface of the README.

I would like to work on this issue. can you assign this issue to me. @RymMichaut 

### Screenshots or Examples (if applicable)

image

### Proposed Solution (optional)

Use badges to add dynamic & real time updating that will show simple stats.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Fixes: #1934 

This PR include changes for the `README.md` file to enhance its visual appeal and provide more information to users, changes mainly focus on addition of several badges and links to external resources.

**Visual enhancements and information addition:**

- Added GitHub stars, issues, pull requests, and license badges to the `README.md` file. 
- Included a **Discord** badge linking to the project's Discord server, a **Docs** badge linking to the project's documentation and a **Release** badge that links to the project's Releases.  

---

@RymMichaut @jrobinAV, raised the PR to solve the #1934 issue, can you review it.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
Here's the result:- 

[taipy-1934.webm](https://github.com/user-attachments/assets/367cf000-a442-431e-b806-c38e533119f5)

**Comment by RymMichaut** [comment]
hey @yashksaini-coder 
Can you limit the badges to the following, as in the attached picture?

remove : issues, PR, stars (we already see them on their own tabs)

- Version (could this be automated with the version in the [doc](https://docs.taipy.io/en/latest/relnotes/))?
- License: Apache 2.0
- Python version needed 3.8
- And three other cards to illustrate the current links:

- [📚 Explore the docs](https://docs.taipy.io/en/latest/)
- [🫱🏼‍🫲🏼 Discord support](https://discord.com/invite/SJyz2VJGxV)
- [👀 Demos & Examples](https://docs.taipy.io/en/latest/gallery/)

See image below:
Capture d'écran 2024-09-09 134713

**Comment by yashksaini-coder** [comment]
> hey @yashksaini-coder Can you limit the badges to the following, as in the attached picture?
> 
> remove : issues, PR, stars (we already see them on their own tabs)
> 
> * Version (could this be automated with the version in the [doc](https://docs.taipy.io/en/latest/relnotes/))?
> * License: Apache 2.0
> * Python version needed 3.8
> * And three other cards to illustrate the current links:
> * [📚 Explore the docs](https://docs.taipy.io/en/latest/)
> * [🫱🏼‍🫲🏼 Discord support](https://discord.com/invite/SJyz2VJGxV)
> * [👀 Demos & Examples](https://docs.taipy.io/en/latest/gallery/)

Okh I will remove the stars, PR badges. Also they have created images for this, I will add custom created icons on canva to match the images
 
image

**Comment by RymMichaut** [comment]
that would be perfect @yashksaini-coder

**Comment by jrobinAV** [comment]
Hi, 

Sorry, but I don't see the added value of having such badges in the readme itself since all the info is already available on the GitHub page.

**Comment by yashksaini-coder** [comment]
> Hi,
> 
> Sorry, but I don't see the added value of having such badges in the readme itself since all the info is already available on the GitHub page.

I understand your point, so I will be closing this PR now.

**Comment by RymMichaut** [comment]
@jrobinAV the added value would be to have stuff more visual than just links.

The idea would be to replace the current links 

- [📚 Explore the docs](https://docs.taipy.io/en/latest/)
- [🫱🏼‍🫲🏼 Discord support](https://discord.com/invite/SJyz2VJGxV)
- [👀 Demos & Examples](https://docs.taipy.io/en/latest/gallery/)

and add the most important info regarding our package

- Version (could this be automated with the version in the [doc](https://docs.taipy.io/en/latest/relnotes/))?
- License: Apache 2.0
- Python version needed 3.8

with visual items.

Check other repos I've selected randomly from the trending repos on GitHub today:

image
image
image
image
image
image
image


this is the standard behavior and exposure.

**Comment by jrobinAV** [comment]
The issue concerns exposing badges for doc, discord, demos, latest release, Python versions, and license. What was proposed in the PR was different. 

I'm okay with the ones in the issue. Also, I believe we can add more badges if they make sense and provide more information. But exposing the # of issues, the # of Pull requests, or the # of stars does not add info.

**Comment by RymMichaut** [comment]
@jrobinAV That's exactly what we agreed on with @yashksaini-coder .

Please reopen the PR @yashksaini-coder and sorry for the misunderstanding

**Pull request closed without merging**
