### PR TITLE
feature/#1986 expand pyarrow version

### LINKED ISSUE #1986: Too much restriction on pyarrow dependency
### What went wrong? 🤔

There is a breaking change in dependencies going from 3.1.1 to 4.0 by a restriction on *pyarrow*. 

Packages like `databricks-sql-connector==3.4.0` cannot be installed now because of this conflict.

```
INFO: pip is looking at multiple versions of taipy to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install databricks-sql-connector==3.4.0 and taipy==4.0.0.dev4 because these package versions have conflicting dependencies.

The conflict is caused by:
    databricks-sql-connector 3.4.0 depends on pyarrow<17 and >=14.0.1
    taipy 4.0.0.dev4 depends on pyarrow<=17.9.9 and >=17.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Expected Behavior

We should be able to install *Taipy* alongside *databricks-sql-connector==3.4.0*. 

### Steps to Reproduce Issue

```
pip install git+https://github.com/Avaiga/taipy.git databricks-sql-connector==3.4.0
```

### Version of Taipy

develop - 10/9/24

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by toan-quach**
#1986

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]
easy enough 👍

**Review by jrobinAV — APPROVED** [review]

**Comment by jrobinAV** [comment]
Must be backported into the branch `release/4.0` as well.

**Comment by FredLL-Avaiga** [comment]
Should this be merged ?

**Comment by jrobinAV** [comment]
YEs.

**Comment by jrobinAV** [comment]
Yes !

**Pull request merged**
