### PR TITLE
Add Image Badges

### LINKED ISSUE #1934: [DOCS] Add Badges
### Issue Description

I would like to add interactive badges in a table format, int the header-section of the README documentation. This will enhance the Engagement & interface of the README.

I would like to work on this issue. can you assign this issue to me. @RymMichaut 

### Screenshots or Examples (if applicable)

image

### Proposed Solution (optional)

Use badges to add dynamic & real time updating that will show simple stats.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by kaioumdev**
fix: #1934
- Added Interactive Badges: Introduced badges for the project version, license, Python version, documentation, support, and demos to improve accessibility.
- Enhanced README Header: Organized the badges in a two-row table format for a cleaner and more structured layout.
- Improved User Engagement: Provided direct links to important resources (documentation, Discord support, and examples), improving navigation and user experience.
- Highlighted Project Requirements: Clearly displayed the project version (v1.1.2) and Python version (3.8) to make requirements more visible.

### CODE REVIEW

**Comment by RymMichaut** [comment]
@kaiyumdev, 
- could you please remove the table and center everything?
- could you please put the Discord official logo?

**Comment by kaioumdev** [comment]
@RymMichaut Yes, I have made the requested changes. The table has been removed, and all content is now centered for a cleaner look. Additionally, I’ve updated the "Discord Support" badge to include the official Discord logo. If there are any other adjustments needed, please let me know; otherwise, this PR is ready for review and merge.

**Comment by RymMichaut** [comment]
Hey, @kaiyumdev thanks for the changes.
However, three things are still to do:
1. On my end, I still see the table, could you check this please?
image

2. Could you fit to Taipy's charter palette: #ff371a / #0b0b0e ?
Here's an example of what another contributor made:
image

3. We don't support 3.8 anymore. Please add also versions 3.9, 3.10, 3.11, 3.12

thanks in advance

**Comment by kaioumdev** [comment]
@RymMichaut Hello, I have resolved the issue with this PR. If there are any further changes or updates needed, please let me know, and I’ll address them right away. Otherwise, please proceed with merging the pull request. Thank you!

**Pull request closed without merging**
