### PR TITLE
Optimising Taipy GUI Installation Script

### PR DESCRIPTION
**Pull request by Ananya54321**
I've made several improvements to the code:

- Better Organization:

Created a TaipyInstaller class to encapsulate all functionality
Split code into smaller, focused methods
Added JSDoc comments for better documentation

- Improved Error Handling:

Added proper error catching and reporting
Included more specific error messages
Added proper promise handling for the installation process

- Code Quality Improvements:

Better variable naming
Consistent code style
Removed duplicate code
Added type hints in JSDoc comments

- Enhanced Features:

Better spinner implementation with proper cleanup
More robust directory checking
Cleaner environment file handling

- Modernization:

Used async/await pattern for better async operation handling
Improved promise handling for the installation process
Better error propagation

### CODE REVIEW

**Comment by FredLL-Avaiga** [comment]
Is this PR based on an opened issue ?
If so can you mention it in the description.

If not, you'll have to provide tests that shows that the new version works at least as well as the old version (ie run the tests with the old version and with the new version)
Then we'll have to decide if the change has any value for the product.

**Review by FredLL-Avaiga — CHANGES_REQUESTED** [review]
Is this PR based on an opened issue ?
If so can you mention it in the description.

If not, you'll have to provide tests that shows that the new version works at least as well as the old version (ie run the tests with the old version and with the new version)
Then we'll have to decide if the change has any value for the product.

**Comment by FredLL-Avaiga** [comment]
Are you still working on this @Ananya54321 ?
If not, we'll close this PR

**Comment by dinhlongviolin1** [comment]
There is no real value added to the execution of the script but thank you again for contributing to Taipy.

**Pull request closed without merging**
