### PR TITLE
Add a validation for date with_time Fixed#1452

### LINKED ISSUE #1452: Add a validation for date with_time
### What would you like to share or ask?

I need to validate a date with_time input created with mardown so that it shows me the minutes by 15, is it possible?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by prathamesh424**
Add a validation for date with_time Fixed #1452

### CODE REVIEW

**Comment by prathamesh424** [comment]
@quest-bot loot #1452

**Comment by prathamesh424** [comment]
@carza06 check out

**Comment by FredLL-Avaiga** [comment]
we don't need a new component that is not usable within Taipy.
Please read and ask questions before PR

**Review by FredLL-Avaiga — CHANGES_REQUESTED** [review]
this will be rejected

**Pull request closed without merging**
