### PR TITLE
Merge Taipy Rest on Taipy

### PR DESCRIPTION
**Pull request by joaoandre-avaiga**
# Bring other repositories to Taipy

For the purpose of demonstrating the process, we will assume that we want to bring `taipy-rest` to `taipy` repository.

1. Make sure both repositories, Taipy and the repository you want to merge are up to date
```bash
$ cd {path_to_taipy} && git checkout develop && git pull
$ cd {path_to_taipy-rest} && git checkout develop && git pull
```
where `{path_to_taipy}` and `{path_to_taipy-rest}` refers to the path of the repositories in your computer.

2. On `{taipy}` add a git remote pointing to your local copy of the repository you want to merge.
```bash
$ git remote add -f rest {path_to_taipy_rest}
```

3. Run `$ git remove -v` on taipy folder to show your taipy git remotes. It should look something like this, using taipy-rest as an example:

```bash
$ git remote add -f rest ../taipy-rest
$ git remove -v
origin	git@github.com:Avaiga/taipy.git (fetch)
origin	git@github.com:Avaiga/taipy.git (push)
rest	../taipy-rest (fetch)
rest	../taipy-rest (push)
```
4. Create a branch on taipy to prepare for the merge
```bash
# on taipy's directory
$ git branch -b merge-x
```
5. Create a branch on the repository to be merged
```bash
# on the directory of the repository that will be merged
$ git branch -b monorepo
```
ps: avoid naming a branch with `/` or `-` in the repository to be merge, it can cause issues with the `git merge` command.

6. Some common files(github workflows, gitignore, linter config files, contributors, readme, etc) will conflic if we try to merge the repository as it is. So it's necessary to temporarily move all the files in the root folder of the repository to be merged to a subfolder, like so:

```bash
# Before: 
├── src
│   ├── taipy
│   |   ├── __init__.py
│   |   ├── rest
│   |   |   ├── api
|   |   |   ....
├── setup.py
├── .github
├── CONTRIBUTING.md
├── ...


# After: 
├── src
│   ├── taipy
│   |   ├── __init__.py
│   |   ├── rest
│   |   |   ├── api
|   |   |   ├── setup.py
|   |   |   ├── .github
|   |   |   ├── CONTRIBUTING.md
|   |   |   ├── ...

```

Some of the files that were moved from root can be deleted and some, like GH actions workflows, can be reused from taipy's main folder. Whatever the case, it should be done after the 2 repositories are merged, can be done in the same PR. Move everything using `git mv`.

```bash
git mv CODE_OF_CONDUCT.md CONTRIBUTING.md contributors.txt .coveragerc .dockerignore .flake8 .flaskenv .gitignore INSTALLATION.md .isort.cfg LICENSE .license-header MANIFEST.in .pre-commit-config.yaml src/taipy/rest
```

7. Verify that all relevant information was moved. All that is left should be files/folders ignored in git or the `.git` folder itself.

```bash
$ ls -lah
drwxrwxr-x  5 joaoandre joaoandre 4,0K nov 15 20:36 .
drwxrwxr-x 12 joaoandre joaoandre 4,0K out 16 17:33 ..
drwxrwxr-x  8 joaoandre joaoandre 4,0K nov 15 20:36 .git
drwxrwxr-x  3 joaoandre joaoandre 4,0K nov 14 22:34 src
```
8. Add the changes and commit. Push is not necessary yet.
```bash
$ git add .
$ git commit -m "chore: prepare repository to merge on taipy"
```
9. Go to taipy's folder and execute the merge command.
```bash
$ cd {path_to_taipy}
$ git merge rest/monorepo  --no-commit --allow-unrelated-histories
Automatic merge went well; stopped before committing as requested
```
Where `rest` refers to the name of the git remote that was created in the begining and `monorepo` refers to the branch name where we made the changes on `taipy-rest`. Please avoid branch names with `/` or `-`, this usually causes errors on the `git merge` command.
10. After the commands is executed with success, the only thing left is to commit, push the changes and open the PR.
```bash
$ git add .
$ git commit -m "chore: merge taipy-rest"
$ git push origin feature/merge-rest
```

### CODE REVIEW

**Comment by joaoandre-avaiga** [comment]
** IMPORTANT **
Taipy rest should be on code freeze from now on. Did we contacted potencial contributors to let them know about this? After merging this PR, we should add a disclaimer on taipy-rest README and archive the taipy-rest repository.

**Comment by joaoandre-avaiga** [comment]
Decisions we have to make:
 1. Should we remove on this PR the redundant files? `CONTRIBUTING.md`, `.coveragerc`, `.flake8`, etc? Or it would be easier to do it in a separete PR?
 2. Should we take this oportunity to try to unify Taipy and Taipy Rest GH actions? Or it would be better on a separate PR?
 3. We need to alter the setup.py, because the line `with open(f"src{os.sep}taipy{os.sep}rest{os.sep}version.json") as version_file:` makes reference to a folder structure that is not true anymore, since we moved the setup.py inside the rest folder, so now `setup.py` and `version.json` are on the same directory. Again should it be done here on in another PR?
 4. Should we move `src/taipy/rest/tests` to the general `tests` folder on Taipy root directory? This implies that we won't package unit tests with each package source code(it's not a deal breaker for me, we just need to decide and replicate to the other repos). And if we move, should we move now or in another PR?
 
 The answer to these questions and any other that may surface is going to compose our development process for this repository migration, If we don't have answers to everything now we could take a couple of days to decide, without problems I think.

**Comment by jrobinAV** [comment]
It looks good to me. Some thoughts: 

1. I have no strong opinion. I would probably do it in a separate PR to ensure consistency across all files to compile.
2. No strong opinion either. I would probably do it as well on a separate PR for the same reason.
3. No opinion.
4. I would move all the tests to a single test folder next to src. I would do it in this PR.

**Review by trgiangdo — COMMENTED** [review]
If possible, I would like to have the test action also runs taipy-rest tests in this PR.

**Comment by joaoandre-avaiga** [comment]
> If possible, I would like to have the test action also runs taipy-rest tests in this PR.

Hey @trgiangdo, since @jrobinAV suggested moving the tests inside the root tests folder of taipy, the current taipy action will run rest tests as well.

**Review by trgiangdo — APPROVED** [review]

**Review by jrobinAV — APPROVED** [review]

**Pull request merged**
