### PR TITLE
Generate common files across taipy repos

### PR DESCRIPTION
**Pull request by AaryaZ**
This PR addresses Issue #106 
PS: Any reviewed changes will be immediately addressed.

### CODE REVIEW

**Comment by AaryaZ** [comment]
@jrobinAV I request you to review this PR as early as possible since there are only two days left for hacktober. Also suggest changes if any that need to be addressed.

**Review by trgiangdo — CHANGES_REQUESTED** [review]
Hello, sorry for the very late review.

Thank you for your contribution. However, I believe the action does not meet the requirement of the issue.

- **Requirement**: Any push or any change in any of the common files on taipy would automatically be pushed across the relevant repositories (namely taipy-config, taipy-core, taipy-gui, taipy-rest).
- The current **copy-common-files** job: Download the common files from the origin develop branch of taipy and push it only on taipy.

To complete the requirement, there should be a job on each sub-repositories, which:
- Detect changes on common files on `taipy`.
- If there is any changes, update its own common files and commit.

Secondly, I believe the "Install Dependencies" step is reduntdant.

**Comment by AaryaZ** [comment]
@trgiangdo Thanks for the detailed explanation of the issue.

**Comment by AaryaZ** [comment]
@trgiangdo I have raised a new Pull request. Pls review it. Thank you.

**Comment by trgiangdo** [comment]
Close due to duplicated

**Pull request closed without merging**
