### PR TITLE
feat: Add support for multiple selection, dropdown, and check mode in…

### LINKED ISSUE #1834: Add drop-down selectors with multiple values
### Description

Hi,
When I use selectors, there isn't a combination that lets me have a multiple-value selector that is also a drop-down. 

### Solution Proposed

Something like drop-down and check boxes for example. The following doesn't give an error but also doesn't "work":

```
tgb.selector
    (...
        multiple=True,
        dropdown=True,
        mode="check",)
```

**Another thing that could be great, is if the callback is only called after I select/unselect all my values (when I go out of the drop-down list). Right now, every time I check a box, it calls on_action, so if I check (or uncheck) a lot of boxes, it calls the Callback many times.**

### Impact of Solution

To give an example, I used a side pane to hold a long list of checkboxes, but it would have been quicker to have this drop-down list, and also more efficient. 

### Additional Context

_No response_

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by akanshSirohi**
… tgb.selector; initial commit

- Implemented multiple selection option
- Enabled dropdown functionality
- Added check mode for dropdown selection

closes #1834

### CODE REVIEW

**Comment by akanshSirohi** [comment]
@quest-bot loot #1834

**Comment by akanshSirohi** [comment]
@FlorianJacta @FredLL-Avaiga @FabienLelaquais Could anyone clarify the remaining requirements for merging this pull request?

**Review by FredLL-Avaiga — CHANGES_REQUESTED** [review]
Looks great
tx @akanshSirohi 
Can you 
- add a screenshot of the new "thing"
- confirm that what worked before continues to work the same (ie the previous tests still work)
- add tests

**Comment by FredLL-Avaiga** [comment]
Are you still working on this @akanshSirohi ?

**Comment by akanshSirohi** [comment]
@FredLL-Avaiga I regret to inform you that, due to immediate time constraints and professional commitments, I am unable to continue with this PR. I am unable to write tests or perform any kind of testing, but I can certainly provide screenshots if needed.

**Comment by FredLL-Avaiga** [comment]
tx for your help @akanshSirohi

**Comment by FredLL-Avaiga** [comment]
This does not preserve the current functionality.
Close

**Pull request closed without merging**
