### PR TITLE
Update contributors.txt

### PR DESCRIPTION
**Pull request by kushal34712**
i have added my username as a contributor to the repo

### CODE REVIEW

**Comment by kushal34712** [comment]
@trgiangdo u can merge this plz

**Comment by trgiangdo** [comment]
When one of your PR is merged, we will merge this as you are a contributor of Taipy.

Thank you for your patience.

**Comment by kushal34712** [comment]
plz accept the changes for readme file

**Comment by jrobinAV** [comment]
done

**Review by jrobinAV — APPROVED** [review]

**Pull request merged**
