### PR TITLE
Feature/#1452 time jump

### LINKED ISSUE #1452: Add a validation for date with_time
### What would you like to share or ask?

I need to validate a date with_time input created with mardown so that it shows me the minutes by 15, is it possible?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Tryxns**
This PR is to resolves #1452.
VERY related to #848: both should share the same code and API.

Sample (Timepicker):
```
from datetime import datetime
from taipy.gui import Gui

time = datetime.today()

page = "<|{time}|time|minute_jump=15|>"

if __name__ == "__main__":
    Gui(page).run(title="Time - Minute Jump")
```

Screenshot 2024-10-29 at 17-21-39 Time - Simple
-----------------------------------------------------------------------------------------------------------------------------------------------------------

Sample (Datepicker):
```
import datetime
from taipy.gui import Gui

date = datetime.datetime.today()

page = "<|{date}|date|with_time|minute_jump=15|>"

if __name__ == "__main__":
    Gui(page).run(title="Date - Minute Jump")
```
Screenshot 2024-10-29 at 17-24-15 Date Range - Simple
-----------------------------------------------------------------------------------------------------------------------------------------------------------

Sample (DateRangepicker):
```
import datetime
from taipy.gui import Gui

start_date = datetime.date(1756, 1, 27)
end_date   = datetime.date(1791, 12, 5)
dates = [start_date, end_date]

page = "<|{dates}|date_range|with_time|minute_jump=15|>"

if __name__ == "__main__":
    Gui(page).run(title="Date Range - Minute Jump")
```
Screenshot 2024-10-29 at 17-25-49 Date Range - Simple
-----------------------------------------------------------------------------------------------------------------------------------------------------------

Bonus, u even can make the minutes jump with different value!

Sample every 10 minutes
Screenshot 2024-10-29 at 17-42-57 Time - Simple

Sample every 6 minutes
Screenshot 2024-10-29 at 17-44-15 Time - Simple

### CODE REVIEW

**Comment by Tryxns** [comment]
ready for your review @FredLL-Avaiga

**Review by FredLL-Avaiga — CHANGES_REQUESTED** [review]
tx @Tryxns Excellent job
Everything is there (except the viselemnts .json)

But I really think this should be manage in conjunction with https://github.com/Avaiga/taipy/pull/2165
What do you think @FabienLelaquais ?

**Comment by Tryxns** [comment]
Ok, will update `viselements.json` in minutes!

May I know what's the difference between `viselements.json` and `factory.py` when we updating the component property?

**Comment by FredLL-Avaiga** [comment]
> Ok, will update `viselements.json` in minutes!
👍 but the main point is that we're not even sure that this should be handled independently of the other issue/PR!
> 
> May I know what's the difference between `viselements.json` and `factory.py` when we updating the component property?
viselements.json is used to generate the doc, class definition for builder and completion/help in VS code via Taipy Studio

**Comment by Tryxns** [comment]
Thanks @FredLL-Avaiga :bulb: a fundamental & important lesson in Taipy framework to know the their function
Done updating `viselements.json`. Looking forward for the decision about this issue & issue 2165 @FabienLelaquais @FredLL-Avaiga

**Comment by FabienLelaquais** [comment]
> tx @Tryxns Excellent job Everything is there (except the viselemnts .json)
> 
> But I really think this should be manage in conjunction with #2165 What do you think @FabienLelaquais ?

You are, as always, completely right @FredLL-Avaiga.
This PR is great... but the issue was not specified enough, and yes, it is completely related to #848 as @FlorianJacta mentioned. 

I will therefore close the PR, not merging it, yet keeping the code for future integration in both `date` and `time` pickers.

The 200 points will be allocated to you no matter what, @Tryxns.
Thanks a lot for your contribution.

**Comment by FabienLelaquais** [comment]
As promised

**Comment by RymMichaut** [comment]
Congratulations for this closed PR.
@Tryxns you'll get your reward all along with the other two packages :)

**Comment by Tryxns** [comment]
merci Rym, Fabien, & Fred :raised_hands:

**Comment by Tryxns** [comment]
@quest-bot loot #1452

**Pull request closed without merging**
