### PR TITLE
Added error handling to NPMInstall build process

### PR DESCRIPTION
**Pull request by iashishkpal**
- Wrapped `subprocess.run` in `try-except` block to catch `CalledProcessError` and `FileNotFoundError`.
- Added detailed error messages for better debugging during frontend build.
- Improved platform compatibility with specific handling for Windows systems.

### CODE REVIEW

**Comment by iashishkpal** [comment]
please merge my pull request .

**Review by FabienLelaquais — APPROVED** [review]
Good idea!

**Review by FredLL-Avaiga — COMMENTED** [review]
Not sure it adds any value
print + raise

**Comment by FredLL-Avaiga** [comment]
Should we close this @FabienLelaquais ?

**Comment by FabienLelaquais** [comment]
Useless.

**Pull request closed without merging**
