### PR TITLE
Add examples for the chat control

### PR DESCRIPTION
**Pull request by FabienLelaquais**
Related to [doc#971](https://github.com/Avaiga/taipy-doc/issues/971).

- Examples for the chat control
- Example for the table control
- Remove fallback hover text in Chat component
- Hide JsonAdapter class
- Minor fixes in reference and elements docs

### CODE REVIEW

**Review by dinhlongviolin1 — DISMISSED** [review]
Nice Avatar

**Comment by FabienLelaquais** [comment]
> Nice Avatar

These are Dall-E generated

**Review by namnguyen20999 — DISMISSED** [review]

**Review by namnguyen20999 — DISMISSED** [review]
Alice looks like she's from a superhero comic :D

**Review by dinhlongviolin1 — APPROVED** [review]
LGTM

**Pull request merged**
