### PR TITLE
Shorten the longest path 

### PR DESCRIPTION
**Pull request by jrobinAV**
adress #1756 
Shorten the longest path  by reducing the sdm folder name and the __ro…ot_folder name

### CODE REVIEW

**Review by FlorianJacta — APPROVED** [review]
LGTM. What about "data_node_management.py" > "data_node_page.py"?

**Comment by jrobinAV** [comment]
> LGTM. What about "data_node_management.py" > "data_node_page.py"?

Since it is not a page, I believe it is confusing. No?
 what about `data_node_mgt.py`

**Comment by FlorianJacta** [comment]
Yes, why not. Maybe, in the future, we will be able to delete this script, as you will be able to upload data with the data node viewer

**Comment by jrobinAV** [comment]
Oh, you are right. And we can already do it in development, right? Did you test it? 
If it works, let's create an issue to remove this partial file.

**Comment by FlorianJacta** [comment]
I did not test it; on my way!

**Review by trgiangdo — APPROVED** [review]
LGTM.

FYI, we can actually shorten it even more.
`__root_folder` --> `__root`
`__main_file` --> `__main`

Those are private variables so it won't affect the user. But I understand that it's probably not needed

**Pull request merged**
