### PR TITLE
Merge Taipy Gui

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Adresses #481.

Tests for  taipy-gui will come later with dedicated github actions as discussed.
The current tests might be failing due to the added tests for taipy-gui.

### CODE REVIEW

**Review by FredLL-Avaiga — DISMISSED** [review]

**Review by FabienLelaquais — CHANGES_REQUESTED** [review]
@dinhlongviolin1 
The 'doc' directory in 'src/taipy/gui' must be move to the root directory: '/doc/gui'.
These are not part of the package source files.

**Comment by dinhlongviolin1** [comment]
> @dinhlongviolin1 The 'doc' directory in 'src/taipy/gui' must be move to the root directory: '/doc/gui'. These are not part of the package source files.

Thanks Fabien!

**Review by FredLL-Avaiga — APPROVED** [review]
still a few test configuration (annotations) to fix ...

**Review by FabienLelaquais — APPROVED** [review]
👌

**Pull request merged**
