### PR TITLE
feat: remove SQL repository

### PR DESCRIPTION
**Pull request by joaoandre-avaiga**

### CODE REVIEW

**Review by toan-quach — DISMISSED** [review]
lgtm! a friendly note that some of the changes should be applied to enterprise repo as well :D

**Comment by toan-quach** [comment]
I forgot but do check taipy-config as well to see if there's any removals to be done

**Comment by jrobinAV** [comment]
The code coverage of `taipy/core/_repository/_base_taipy_model.py` is slightly low. Can you check if we can improve the coverage of this class?

**Review by jrobinAV — DISMISSED** [review]

**Comment by joaoandre-avaiga** [comment]
> I forgot but do check taipy-config as well to see if there's any removals to be done

I've checked config, theres no direct reference to sql repo, only the repository attributes(type, properties), we should be good. I'll check enterprise if theres anything to be done.

**Comment by joaoandre-avaiga** [comment]
> The code coverage of `taipy/core/_repository/_base_taipy_model.py` is slightly low. Can you check if we can improve the coverage of this class?

I've added specif tests for the base_model class. There are 2 abstract methods still not covered, but they don't have any logic to be tested. So this should be enough.

**Review by trgiangdo — DISMISSED** [review]
This is looking good. Thank you Joao

**Review by jrobinAV — DISMISSED** [review]
As people were saying in the 50's: 
"Rock-and-roll"...

**Review by jrobinAV — APPROVED** [review]

**Review by trgiangdo — APPROVED** [review]

**Pull request merged**
