### PR TITLE
Change versions to 4.0.0.dev0

### PR DESCRIPTION
**Pull request by jrobinAV**

### CODE REVIEW

**Review by FredLL-Avaiga — DISMISSED** [review]
but then we need to change the frontend versions too ...

**Comment by jrobinAV** [comment]
> but then we need to change the frontend versions too ...

I don't know abt that. Can you do it directly in this branch?

**Comment by FredLL-Avaiga** [comment]
you'll have to wait for my PR to be merged :-D

**Comment by jrobinAV** [comment]
> /frontend/taipy-gui

Sure. No rush on my side.

**Review by FabienLelaquais — APPROVED** [review]
👌

**Review by dinhlongviolin1 — APPROVED** [review]
Thanks JR

**Review by toan-quach — APPROVED** [review]

**Review by namnguyen20999 — APPROVED** [review]

**Review by FredLL-Avaiga — APPROVED** [review]

**Pull request merged**
