### PR TITLE
Added handle-issues.yml to clean up no response sections

### PR DESCRIPTION
**Pull request by AdityaS8804**
### Issue :  
#1357

### Change made :  
- .github/workflows/handle-issues.yml file created 
### Funtion of the code :  
- Is a github action which is invoked when an issue is opened.  
### Detail :  
- It cleans up 'No response', 'NA' and 'N/A' sections from the issue submitted and updates the same issue.

### CODE REVIEW

**Review by jrobinAV — COMMENTED** [review]
I love your proposal, @AdityaS8804 . And it's a high-quality PR. Thanks a lot. 

Give me some time to test the cation. I'll try to do it tomorrow. or within the next few days.

By the way, @FabienLelaquais is a huge fan of Regex, he should be pleased to review the PR as well.

**Review by jrobinAV — DISMISSED** [review]
Thanks a lot!

**Review by FabienLelaquais — COMMENTED** [review]
👍

**Review by FabienLelaquais — DISMISSED** [review]
Neat.

**Review by jrobinAV — APPROVED** [review]

**Comment by AdityaS8804** [comment]
Hi ,
@jrobinAV Thank you for your continued support throughout this process. As this is my first open-source contribution, I’m glad everything has been progressing smoothly. I also appreciate your review, @FabienLelaquais.     
Among the tests, it is mentioned that 5 workflows require approval from a maintainer. Could you please look into the same?  

Thank you once again for your assistance.

**Pull request merged**
