### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SohaibBaig1243**

### CODE REVIEW

**Comment by SohaibBaig1243** [comment]
I have updated this file

**Comment by FlorianJacta** [comment]
What is the goal of this PR? What issue do you want to address?

**Review by florian-vuillemot — CHANGES_REQUESTED** [review]
IMHO this does not improve the readability of the file.

**Comment by jrobinAV** [comment]
I agree with @florian-vuillemot . The file readability is degraded while the result does not change.

With any more motivation (or description) for this PR, I reject it.

**Pull request closed without merging**
