### PR TITLE
Fix: Handled Typo errors in readme.md file

### PR DESCRIPTION
**Pull request by moli-debugger**

### CODE REVIEW

**Comment by moli-debugger** [comment]
I found grammatical errors and missing punctuation in the README.md file. Over 20 typos have been fixed. Please review and accept the PR. 

Thank you!

**Review by RymMichaut — DISMISSED** [review]

**Comment by moli-debugger** [comment]
Resloving merge Conflicting file

**Comment by moli-debugger** [comment]
@RymMichaut The merge conflicts is resloved, kindly reqyesting to review and approve the PR.

Thank you.

**Review by RymMichaut — APPROVED** [review]

**Comment by moli-debugger** [comment]
@RymMichaut The build is succeeded, requesting you to merge the branch with source branch. 

Thank you.

**Comment by RymMichaut** [comment]
@moli-debugger  we'll merge it with all the others ASAP. Until then, I'll put the label hacktoberfest solved

**Comment by jrobinAV** [comment]
This PR is not linked to any hacktoberfest-labeled issue. We cannot put the hacktoberfest approved label on it. Sorry about that, and thank you for your understanding.

**Pull request merged**
