### PR TITLE
tree does not support mode

### LINKED ISSUE #2278: [🐛 BUG] The checkbox / radio mode does not work in tree view
### What went wrong? 🤔

The following snippet ignores the mode ("check" or "radio") and only returns a normal tree, despite being described otherwise in the documentation.

```python
tgb.tree( "{x}", mode="check", lov="{lov}" )
```

### Expected Behavior

Behave like:
```python
tgb.selector( "{x}", mode="check", lov="{lov}" )
```

### Steps to Reproduce Issue

1. Run
```python
x = ""
lov = [{'id': '1', 'label': 'P', 'children': [{'id': '2', 'label': 'C1', 'children': []}, {'id': '3', 'label': 'C2', 'children': []}]}]

with tgb.Page() as root:
    tgb.text( "Here's a Tree:")
    tgb.tree( "{x}",
        mode="check", lov="{lov}" )
    tgb.text( "Here's a Selector:")
    tgb.selector( "{x}",
        mode="check", lov="{lov}" )    

gui = Gui(page=root)

if __name__ == "__main__":
    gui.run( port=4999 )
```
2. Look for checkboxes in the tree.

### Solution Proposed

Implement "mode" in
https://github.com/Avaiga/taipy/blob/348d86d5f75b19dcfd9bb22c6721aebca5486709/frontend/taipy-gui/src/components/Taipy/TreeView.tsx#L146
, like in 
https://github.com/Avaiga/taipy/blob/348d86d5f75b19dcfd9bb22c6721aebca5486709/frontend/taipy-gui/src/components/Taipy/Selector.tsx#L128

### Browsers

Firefox

### OS

Windows

### Version of Taipy

4.0.1

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by FredLL-Avaiga**
resolves #2278

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description
Tree does not support property `mode`

## Related Tickets & Documents
- Closes #2278 

## How to reproduce the issue

```py
import taipy.gui.builder as tgb
from taipy.gui import Gui

x = ""
lov = [
    {
        "id": "1",
        "label": "P",
        "children": [{"id": "2", "label": "C1", "children": []}, {"id": "3", "label": "C2", "children": []}],
    }
]

with tgb.Page() as root:
    tgb.text("Here's a Tree:")
    tgb.tree("{x}", mode="check", lov="{lov}")
    tgb.text("Here's a Selector:")
    tgb.selector("{x}", mode="check", lov="{lov}")

if __name__ == "__main__":
    Gui(root).run(title="2278 [🐛 BUG] The checkbox / radio mode does not work in tree view")

```

### CODE REVIEW

**Review by FabienLelaquais — APPROVED** [review]
😶

**Review by dinhlongviolin1 — APPROVED** [review]
Ez one for you

**Comment by sumanth-tccc** [comment]
Hi Guys . The dropdown also is not working like <|..|selector|dropdown=True|>

**Comment by sumanth-tccc** [comment]
```py
x = ""
lov = [
    {
        "id": "1",
        "label": "P",
        "children": [
                           {"id": "1.2", "label": "C1", "children": []},
                           {"id": "1.3", "label": "C2", "children": []}
                          ],
    },
    {
        "id": "2",
        "label": "q",
        "children": [
                           {"id": "2.2", "label": "Q1", "children": []},
                           {"id": "2.3", "label": "Q2", "children": []}
                          ],
    },
]

with tgb.Page() as root:
    tgb.text("Here's a Tree:")
    tgb.tree("{x}", mode="check", lov="{lov}")
    tgb.text("Here's a Selector:")
    tgb.selector("{x}", mode="check", lov="{lov}")

if __name__ == "__main__":
    Gui(root).run(title="2278 [🐛 BUG] The checkbox / radio mode does not work in tree view")
```


The drop down true keeps all of them active

**Pull request merged**
