### PR TITLE
Support python 312 actions

### LINKED ISSUE #627: Python 3.12 Support
Taipy must support Python 3.12.

- [ ] Update the documentation
- [x] Update the GitHub templates
- [x] Update the GitHub actions.
- [x] Run tests
- [x] README files

### PR DESCRIPTION
**Pull request by joaoandre-avaiga**
resolves #627

### CODE REVIEW

**Review by jrobinAV — DISMISSED** [review]
OK for me.
can you just check my commit before merging?

**Comment by jrobinAV** [comment]
Test actions on 3.12 and mac os don't work yet.

**Comment by joaoandre-avaiga** [comment]
> Test actions on 3.12 and mac os don't work yet.

The action timeout because it took 30 minutes to install the dependencies.

**Review by jrobinAV — APPROVED** [review]
Looks good to me. 
Can you update taipy-doc and/or create a ticket for that?

**Pull request merged**
