### PR TITLE
Table cell style not applied when columns refreshed with rebuild=True

### LINKED ISSUE #2005: [🐛 BUG] Table cell style not applied when columns refreshed with rebuild=True
### What went wrong? 🤔

Code example:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb
import pandas as pd
import numpy as np

X_KEY = "x"
Y_KEY = "y"

def get_df():
    df = pd.DataFrame({X_KEY: range(100)})
    df[Y_KEY] = np.sin(df[X_KEY])
    return df

empty_table = pd.DataFrame(None)
df = empty_table


def cell_style(state, value, index, row, column_name):
    if value >= 0:
        return "bg-secondary"
    else:
        return ""


def row_style(state, index, row):
    if Y_KEY in row and row[Y_KEY] >= 0:
        return "bg-secondary"
    else:
        return ""


with tgb.Page() as page_tgb:
    tgb.button(label="Toggle df", on_action=lambda s: s.assign("df", get_df() if s.df.equals(empty_table) else empty_table))
    with tgb.layout(columns="1 1 1"):
        with tgb.part():
            tgb.text("Does NOT work: cell_class_name")
            tgb.table("{df}", rebuild=True, page_size=10, **{f"cell_class_name__{Y_KEY}": cell_style})
        with tgb.part():
            tgb.text("Works: row_class_name")
            tgb.table("{df}", rebuild=True, page_size=10, row_class_name=row_style)
        with tgb.part():
            tgb.text("Works: cell_class_name, but df isn't 'rebuilt'")
            tgb.table("{get_df()}", rebuild=True, page_size=10, **{f"cell_class_name__{Y_KEY}": cell_style})


def on_change(state, var_name: str, var_value):
    print(var_name, type(var_value), var_value)


if __name__ == "__main__":
    gui = Gui(page_tgb)
    gui.run(debug=True, run_browser=False, use_reloader=True)
```

Before clicking button:
image

After clicking button:
image

### Expected Behavior

The cell style should be applied when columns are refreshed when `rebuild=True`.

### Steps to Reproduce Issue

Run example code above

### Browsers

Chrome

### OS

Windows, Linux

### Version of Taipy

4.0.0

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by FredLL-Avaiga**
resolves #2005

```py
import numpy as np
import pandas as pd

import taipy.gui.builder as tgb
from taipy.gui import Gui

X_KEY = "x"
Y_KEY = "y"

def get_df():
    df = pd.DataFrame({X_KEY: range(100)})
    df[Y_KEY] = np.sin(df[X_KEY])
    return df

empty_table = pd.DataFrame(None)
df = empty_table


def cell_style(state, value, index, row, column_name):
    if value >= 0:
        return "bg-secondary"
    else:
        return ""


def row_style(state, index, row):
    if Y_KEY in row and row[Y_KEY] >= 0:
        return "bg-secondary"
    else:
        return ""


with tgb.Page() as page_tgb:
    tgb.button(label="Toggle df", on_action=lambda s: s.assign("df", get_df() if s.df.equals(empty_table) else empty_table))
    with tgb.layout(columns="1 1 1"):
        with tgb.part():
            tgb.text("Does NOT work: cell_class_name")
            tgb.table("{df}", rebuild=True, page_size=10, **{f"cell_class_name__{Y_KEY}": cell_style})
        # with tgb.part():
        #     tgb.text("Works: row_class_name")
        #     tgb.table("{df}", rebuild=True, page_size=10, row_class_name=row_style)
        # with tgb.part():
        #     tgb.text("Works: cell_class_name, but df isn't 'rebuilt'")
        #     tgb.table("{get_df()}", rebuild=True, page_size=10, **{f"cell_class_name__{Y_KEY}": cell_style})


def on_change(state, var_name: str, var_value):
    print(var_name, type(var_value), var_value)


if __name__ == "__main__":
    gui = Gui(page_tgb)
    gui.run(title="2005 [🐛 BUG] Table cell style not applied when columns refreshed with rebuild=True")

```

### CODE REVIEW

**Review by FabienLelaquais — DISMISSED** [review]
🫤

**Review by dinhlongviolin1 — DISMISSED** [review]

**Review by mohizzzol — COMMENTED** [review]
really 2 lines?

**Comment by FlorianJacta** [comment]
What about *format_fn*?

**Comment by FlorianJacta** [comment]
I feel like this should be backported. I think I saw this issue in a client's app but didn't know what it was with *format_fn*

What do you think? @FabienLelaquais @FredLL-Avaiga

**Comment by FredLL-Avaiga** [comment]
I think we should backport it as it is the result of the property name change from `style`.
@FabienLelaquais ?

**Review by FabienLelaquais — APPROVED** [review]
👌 + backport, thanks!

**Pull request merged**
