### PR TITLE
Implemented fc on grid layout which applies min-width to the card inside, hence no need to add explicit width

### LINKED ISSUE #1780: Allow a Stylekit "card" to be side-by-side with width=fit-content
### Description

Cards can have their width match the size of its content with #468, which is great for displaying metrics (among other things).

I'd like to position cards side-by-side, **without needing to use a layout and explicitly defining the width of each element there**.

Currently, I can use a layout and define the width:

```python
from taipy.gui import Gui, Markdown

page_md_target = Markdown(
"""
<|layout|columns=10em 10em|

<|card|part|width=fit-content|
Metric 1
|>

<|card|part|width=fit-content|
Metric 2
|>

|>
""")

if __name__ == "__main__":
    gui = Gui(page_md_target)
    gui.run(debug=True, run_browser=False, use_reloader=True, dark_mode=False)
```

Which produces:

image

I want to create this without defining a width anywhere.

### Solution Proposed

Maybe allowing a layout column to "fit-content" ("fc") is a possible solution? I don't like the extra nesting especially if I'm only showing 2 cards, but it makes sense and I can also use layout.gap to add space between the cards.

```python
page_md_layout = Markdown(
"""
<|layout|columns=fc fc|

<|card|part|width=fit-content|
Metric 1
|>

<|card|part|width=fit-content|
Metric 2
|>

|>
""")
```

### Impact of Solution

Needs to work with taipy.gui.builder / tgb also.

### Additional Context

_No response_

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by HatimZ**
resolves #1780 

1. Modified Layout file to map fc to min-width
2. Added a Test case 
3. Ran tests
4. Ran pre-commit
5. Tested Locally with a python script with the proposed code provided in issue

### CODE REVIEW

**Comment by HatimZ** [comment]
@quest-bot loot #1780

**Comment by HatimZ** [comment]
@arcanaxion

**Review by FredLL-Avaiga — CHANGES_REQUESTED** [review]
Tx @HatimZ 
I like your solution, it is simple and neat.
We would need a bit of documentation and also an example in doc/gui/examples.
👍

**Comment by HatimZ** [comment]
> Tx @HatimZ I like your solution, it is simple and neat. We would need a bit of documentation and also an example in doc/gui/examples. 👍

Okay sure!

**Comment by FabienLelaquais** [comment]
@HatimZ Indeed this is short and effective.
In order for us to integrate this, as @FredLL-Avaiga said, we would like a little something to expose it to users:
- A short and relevant application that demonstrates the feature.
  There are a few such examples in [taipy]/doc/gui/examples/[controls|blocks] that you can get inspiration from.
  So far we have no example for the `layout` block, and we need to work on it.
  We can certainly be in charge of fitting your proposal there, with code conventions and formatting constraints.
- A paragraph or two explaining, beside the code comments, what's going on.
  We will transform this input into a Usage section in the documentation, pointing to the code example we would have integrated.
  
  Thanks!

**Comment by HatimZ** [comment]
#2039
Thankyou for the feedback, will wrap it up today.

**Comment by FredLL-Avaiga** [comment]
Are you still working on this PR @HatimZ  ?
If you are, please update your branch and answer the questions
If you are not, please close the PR

**Comment by FredLL-Avaiga** [comment]
layout columns property already supports standard css : we're not inventing new keywords
Tx for your time and efforts @HatimZ 
We should have better analyzed the issue at first

**Comment by RymMichaut** [comment]
hey @HatimZ  congratulations on the merged PR.
could you please contact me at rym.michaut@taipy.io to ship your swag? :)

**Pull request closed without merging**
