### PR TITLE
bug/ move template test files to general test folder

### PR DESCRIPTION
**Pull request by toan-quach**

### CODE REVIEW

**Review by gmarabout — DISMISSED** [review]
Thank you! 🙏🏻

**Review by jrobinAV — DISMISSED** [review]

**Review by jrobinAV — COMMENTED** [review]
It looks like with have issues on windows os

**Review by florian-vuillemot — DISMISSED** [review]

**Review by gmarabout — DISMISSED** [review]
LGTM. Do you know what is going on with the CI on Windows?

**Comment by toan-quach** [comment]
@gmarabout not sure either :/

**Comment by FredLL-Avaiga** [comment]
> LGTM. Do you know what is going on with the CI on Windows?

it seems windows console output latin-1 instead of utf-8

**Review by FredLL-Avaiga — APPROVED** [review]

**Review by trgiangdo — APPROVED** [review]
Thank you @toan-quach and @FredLL-Avaiga

**Review by jrobinAV — APPROVED** [review]

**Pull request merged**
