### PR TITLE
pre-announcing hacktoberfest

### PR DESCRIPTION
**Pull request by RymMichaut**
adding a banner to announce the Hacktoberfest 2024

### CODE REVIEW

**Review by FabienLelaquais — APPROVED** [review]
👌

**Review by jrobinAV — APPROVED** [review]
Neat!

**Comment by RymMichaut** [comment]
thank you :)

Can you merge it? I don't have the rights


Regards,
------
*PS*: I don't work on Wednesdays

<https://www.linkedin.com/in/rymguerbi/> <https://github.com/RymMichaut>


Rym Michaut

Global Community Manager

***@***.***

+33 6 72 40 28 44


Le jeu. 19 sept. 2024 à 11:37, Jean-Robin ***@***.***> a
écrit :

**Comment by RymMichaut** [comment]
merci :)


Regards,
------
*PS*: I don't work on Wednesdays

<https://www.linkedin.com/in/rymguerbi/> <https://github.com/RymMichaut>


Rym Michaut

Global Community Manager

***@***.***

+33 6 72 40 28 44


Le jeu. 19 sept. 2024 à 11:42, Jean-Robin ***@***.***> a
écrit :

**Pull request merged**
