### PR TITLE
link-changed

### PR DESCRIPTION
**Pull request by marisogo**
changed link to demos that wasn't working

### CODE REVIEW

**Review by FlorianJacta — APPROVED** [review]

**Review by jrobinAV — APPROVED** [review]

**Review by FabienLelaquais — APPROVED** [review]
👍

**Review by jrobinAV — COMMENTED** [review]
Good.

This PR could also be the opportunity to update the Taipy logo.

**Comment by jrobinAV** [comment]
@marisogo, Any update on this PR? On the Taipy logo?

**Comment by marisogo** [comment]
@jrobinAV we will probably other changes when we change the logo, this will probably take a little time, for now it's important that this link works

**Pull request merged**
