### PR TITLE
Support direct taipy installation on dev branches

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Solve Avaiga/taipy-enterprise#208

To test it out, you can run this command and verify that `src/taipy/gui_core/lib` is available in python site-packages
```
pip install "taipy@git+https://git@github.com/Avaiga/taipy.git@feature/direct-taipy-installation
```

### CODE REVIEW

**Review by FredLL-Avaiga — DISMISSED** [review]
I suppose you know that node.js is installed...
Well done anyway

**Review by joaoandre-avaiga — DISMISSED** [review]

**Comment by dinhlongviolin1** [comment]
> I suppose you know that node.js is installed...
> Well done anyway

Thanks Fred. The problem with this one is the package is not installed on pip during the execution of the build_py process. Because of that, we need to get the temporary 'backend' installation path as they call it and use that to locate the taipy-gui package.

**Comment by jrobinAV** [comment]
Worked for me!
Thx

**Review by jrobinAV — DISMISSED** [review]

**Review by FabienLelaquais — DISMISSED** [review]
👍

**Review by jrobinAV — APPROVED** [review]

**Pull request merged**
